name = "test_project"
uuid = "fe46fda2-06b3-4cd3-b868-4c4d158237ea"
authors = ["PseudoFractal <kshitishkumarratha@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
DataFrames = "1.8.0"
Plots = "1.41.1"
